export const CUSTOM_KEY_MAPPING: Record<string, string> = {
  ArrowUp: "up",
  ArrowDown: "down",
  ArrowLeft: "left",
  ArrowRight: "right",
  AltLeft: "alt",
  AltRight: "alt",
  ControlLeft: "control",
  ControlRight: "control",
  ShiftLeft: "shift",
  ShiftRight: "right_shift",
  Numpad1: "numpad_1",
  Numpad2: "numpad_2",
  Numpad3: "numpad_3",
  Numpad4: "numpad_4",
  Numpad5: "numpad_5",
  Numpad6: "numpad_6",
  Numpad7: "numpad_7",
  Numpad8: "numpad_8",
  Numpad9: "numpad_9",
  Numpad0: "numpad_0",
};
